# Need to create a seperate container for postgresql database
# Additionally, ensuring that the database data is persistent and not lost when the containers are restarted.
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: psql
data:
  POSTGRES_DB: testdb
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  PGDATA: /var/lib/postgresql/data/k8s
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: psql
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
      path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  selector:
    matchLabels: 
      app: psql
      type: local
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels: 
    app: psql 
    type: local
spec:
  replicas: 2
  selector:
    matchLabels:
      app: psql
      type: local
  template:
    metadata:
      labels:
        app: psql
        type: local
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: postgressql
        image: postgres:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        resources:
          requests:
             memory: "512Mi"   # Request at least 512MB of memory
             cpu: "250m"       # Request at least 250 milliCPU (0.25 CPU core)
          limits:
             memory: "1Gi"     # Limit memory usage to 1GB
             cpu: "500m"       # Limit CPU usage to 500 milliCPU (0.5 CPU core)
        envFrom:
        - configMapRef:
           name: postgres-secret
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name:  psql-service-np
spec:
  selector:
    app:  psql
    type: local
  type:  ClusterIP
  ports:
  - name:  psql
    port:  5432
    protocol: TCP
